/**
 * A BIBLIOTECA DE DESENHOS do Picross da Malha — feita à mão, formas
 * genéricas do universo aconchegante do pet (nenhum personagem de franquia).
 *
 * `'#'` = casa pintada, `'.'` = vazia. Toda grade é quadrada (5, 7 ou 10).
 * ⚠️ Todo desenho tem de sair INTEIRO só por lógica de linha, sem chute:
 * `picross.test.ts` roda o resolvedor em cada um. Desenho que não passa é
 * redesenhado — nunca aceito com "tem mais de uma resposta".
 */
export interface PicrossPattern {
  id: string;
  namePt: string;
  nameEn: string;
  rows: readonly string[];
}

export const PICROSS_PATTERNS: readonly PicrossPattern[] = [
  // ---------------------------------------------------------------- 5×5
  { id: 'coracao', namePt: 'Coração', nameEn: 'Heart', rows: [
    '.#.#.',
    '#####',
    '#####',
    '.###.',
    '..#..',
  ] },
  { id: 'estrela', namePt: 'Estrela', nameEn: 'Star', rows: [
    '..#..',
    '.###.',
    '#####',
    '.###.',
    '.#.#.',
  ] },
  { id: 'lua', namePt: 'Lua', nameEn: 'Moon', rows: [
    '.###.',
    '##...',
    '##...',
    '##...',
    '.###.',
  ] },
  { id: 'gota', namePt: 'Gota', nameEn: 'Drop', rows: [
    '..#..',
    '.###.',
    '#####',
    '#####',
    '.###.',
  ] },
  { id: 'sino', namePt: 'Sino', nameEn: 'Bell', rows: [
    '..#..',
    '.###.',
    '.###.',
    '#####',
    '..#..',
  ] },
  { id: 'folha', namePt: 'Folha', nameEn: 'Leaf', rows: [
    '..###',
    '.####',
    '#####',
    '####.',
    '#....',
  ] },
  { id: 'ovo', namePt: 'Ovo', nameEn: 'Egg', rows: [
    '.###.',
    '##.##',
    '#####',
    '#####',
    '.###.',
  ] },
  // ---------------------------------------------------------------- 7×7
  { id: 'cogumelo', namePt: 'Cogumelo', nameEn: 'Mushroom', rows: [
    '..###..',
    '.##.##.',
    '#######',
    '##.#.##',
    '..###..',
    '..#.#..',
    '..###..',
  ] },
  { id: 'nuvem', namePt: 'Nuvem', nameEn: 'Cloud', rows: [
    '.......',
    '..##...',
    '.####..',
    '.######',
    '#######',
    '#######',
    '.#####.',
  ] },
  { id: 'chama', namePt: 'Chama', nameEn: 'Flame', rows: [
    '...#...',
    '..##...',
    '..###.#',
    '.#####.',
    '###.###',
    '##...##',
    '.#####.',
  ] },
  { id: 'cristal', namePt: 'Cristal', nameEn: 'Crystal', rows: [
    '...#...',
    '..###..',
    '.##.##.',
    '###.###',
    '.##.##.',
    '..###..',
    '...#...',
  ] },
  { id: 'fantasminha', namePt: 'Fantasminha', nameEn: 'Tiny ghost', rows: [
    '..###..',
    '.#####.',
    '##.#.##',
    '#######',
    '#######',
    '#######',
    '#.#.#.#',
  ] },
  { id: 'broto', namePt: 'Broto', nameEn: 'Sprout', rows: [
    '.##..##',
    '###.###',
    '.##.##.',
    '..###..',
    '...#...',
    '.#####.',
    '..###..',
  ] },
  { id: 'chave', namePt: 'Chave', nameEn: 'Key', rows: [
    '..###..',
    '.##.##.',
    '..###..',
    '...#...',
    '...###.',
    '...#...',
    '...##..',
  ] },
  // ---------------------------------------------------------------- 10×10
  { id: 'casinha', namePt: 'Casinha', nameEn: 'Little house', rows: [
    '....##....',
    '...####...',
    '..######..',
    '.########.',
    '##########',
    '.########.',
    '.##.##.##.',
    '.##.##.##.',
    '.#####.##.',
    '.########.',
  ] },
  { id: 'peixe', namePt: 'Peixe', nameEn: 'Fish', rows: [
    '..........',
    '...####...',
    '..######.#',
    '.##.#####.',
    '#########.',
    '#########.',
    '.########.',
    '..######.#',
    '...####...',
    '..........',
  ] },
  { id: 'bichano', namePt: 'Bichano', nameEn: 'Whiskers', rows: [
    '#........#',
    '##......##',
    '###....###',
    '##########',
    '##.####.##',
    '##########',
    '####..####',
    '.###..###.',
    '..######..',
    '...####...',
  ] },
  { id: 'pena', namePt: 'Pena', nameEn: 'Feather', rows: [
    '.....##...',
    '....####..',
    '...######.',
    '...##.###.',
    '..###.##..',
    '..##.###..',
    '..###.#...',
    '...###....',
    '...#......',
    '..#.......',
  ] },
  { id: 'lua-grande', namePt: 'Lua crescente', nameEn: 'Crescent moon', rows: [
    '...####...',
    '..##......',
    '.##.......',
    '###.......',
    '###.......',
    '###.......',
    '###.......',
    '.##.......',
    '..##......',
    '...####...',
  ] },
  { id: 'arvorezinha', namePt: 'Arvorezinha', nameEn: 'Little tree', rows: [
    '....##....',
    '...####...',
    '..######..',
    '.########.',
    '..######..',
    '.########.',
    '##########',
    '....##....',
    '....##....',
    '..######..',
  ] },
  { id: 'estrelona', namePt: 'Estrela grande', nameEn: 'Big star', rows: [
    '....##....',
    '....##....',
    '...####...',
    '##########',
    '.########.',
    '..######..',
    '..######..',
    '.###..###.',
    '.##....##.',
    '##......##',
  ] },
  { id: 'sino-grande', namePt: 'Sino grande', nameEn: 'Big bell', rows: [
    '....##....',
    '...####...',
    '..######..',
    '..######..',
    '..######..',
    '.########.',
    '.########.',
    '##########',
    '..........',
    '....##....',
  ] },
];
