export const STORAGE_KEYS = {
  GAME_STATE: 'digiapp_state_v3',
  AI_SETTINGS: 'digiapp-ai-settings',
  THEME: 'digiapp-theme',
  LANGUAGE: 'digiapp-language',
  ONBOARDING_COMPLETE: 'digiapp-onboarding-complete',
  USER_NAME: 'digiapp-user-name',
  EGG_TYPE: 'digiapp-egg-type',
  FIRST_TASK_POPUP_SHOWN: 'digiapp-first-task-popup-shown',
  NOTIFICATIONS_ENABLED: 'digiapp-notifications-enabled',
  PWA_INSTALL_DISMISSED: 'digiapp-pwa-install-dismissed',
  NOTIFICATION_PROMPT_DISMISSED: 'digiapp-notification-prompt-dismissed',
  SCHEDULED_NOTIFICATIONS: 'digiapp-scheduled-notifications',
  DAILY_NOTIFICATION_CHECK: 'digiapp-daily-notification-check',
  SAVE_ID: 'digiapp-save-id',
  USER_EMAIL: 'digiapp-user-email',
  IS_SLEEPING: 'digiapp-is-sleeping',
  FOOD_FEED_TIMES: 'digiapp-food-feed-times',
  RUB_HEAL_DAY: 'digiapp-rub-heal-day',
  DAILY_REPORT_SHOWN: 'digiapp-daily-report-shown',
  RUB_HINT_SHOWN: 'digiapp-rub-hint-shown',
  AUTO_SLEEP_ENABLED: 'digiapp-auto-sleep-enabled',
  AUTO_SLEEP_START: 'digiapp-auto-sleep-start',
  AUTO_SLEEP_END: 'digiapp-auto-sleep-end',
  DUNGEON_DIFFICULTY: 'digiapp-dungeon-difficulty',
  DUNGEON_BEST: 'digiapp-dungeon-best',
  DUNGEON_HEART_DROPS: 'digiapp-dungeon-heart-drops',
  DINO_BEST: 'digiapp-dino-best',
  SOUND_MUTED: 'digiapp-sound-muted',
  FCM_TOKEN: 'digiapp-fcm-token',
  LAST_CLOUD_SYNC: 'digiapp-last-cloud-sync',
  ORACLE_FORM: 'digiapp-oracle-form',
  // Soulmon: perfil da alma gerado no onboarding (input + seed p/ regenerar)
  SOULMON_PROFILE: 'soulmon-profile',
  // Monetização — cap diário de criação de atividade/tarefa no modo demo
  DEMO_TASKS_CREATED_TODAY: 'soulmon-demo-tasks-created-today',
  // Segundo onboarding: tutorial do jogo + criação obrigatória da 1ª tarefa
  TUTORIAL_COMPLETE: 'soulmon-tutorial-complete',
  // Login por link de e-mail: o Firebase exige reconfirmar o e-mail ao
  // completar o login, então ele fica guardado entre o envio e o retorno.
  PENDING_LOGIN_EMAIL: 'soulmon-pending-login-email',
} as const;
